repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        exclude: "yarn.lock"
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.7.1
  #   hooks:
  #     - id: prettier
  #       exclude: "CHANGELOG.md|docs"
  #       args: ["--print-width=150", "--tab-width=2", "--single-quote=false", "--trailing-comma=es5", "--bracket-same-line=false"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ["--exclude-lines", "secretsmanager:"]
